"""phase3 publication buyer tables

Revision ID: 1a0dff07b31d
Revises: 281aa5f944b6
Create Date: 2026-09-08 05:22:21.804463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a0dff07b31d'
down_revision: Union[str, None] = '281aa5f944b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_subscriptions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('p256dh', sa.String(), nullable=False),
    sa.Column('auth', sa.String(), nullable=False),
    sa.Column('ua', sa.String(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    op.create_index(op.f('ix_push_subscriptions_user_id'), 'push_subscriptions', ['user_id'], unique=False)
    op.create_table('dnbp_publications',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('published_by', sa.UUID(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('engine_version', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('superseded_by', sa.UUID(), nullable=True),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['published_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['order_snapshots.id'], ),
    sa.ForeignKeyConstraint(['superseded_by'], ['dnbp_publications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dnbp_publications_org_id'), 'dnbp_publications', ['org_id'], unique=False)
    op.create_index(op.f('ix_dnbp_publications_published_at'), 'dnbp_publications', ['published_at'], unique=False)
    op.create_index(op.f('ix_dnbp_publications_snapshot_id'), 'dnbp_publications', ['snapshot_id'], unique=False)
    op.create_table('dnbp_publication_deliveries',
    sa.Column('publication_id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('WS', 'PUSH', 'POLL', name='delivery_channel'), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['publication_id'], ['dnbp_publications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dnbp_publication_deliveries_buyer_id'), 'dnbp_publication_deliveries', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_dnbp_publication_deliveries_publication_id'), 'dnbp_publication_deliveries', ['publication_id'], unique=False)
    op.create_table('dnbp_publication_lines',
    sa.Column('publication_id', sa.UUID(), nullable=False),
    sa.Column('species', sa.String(), nullable=False),
    sa.Column('dnbp_per_kg', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('target_heads', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('target_weight_kg_min', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('target_weight_kg_max', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('contributing_line_ids', sa.ARRAY(sa.UUID()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['publication_id'], ['dnbp_publications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dnbp_publication_lines_publication_id'), 'dnbp_publication_lines', ['publication_id'], unique=False)
    op.create_table('buy_entries',
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('saleyard', sa.String(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('species', sa.String(), nullable=False),
    sa.Column('agent', sa.String(), nullable=True),
    sa.Column('pen', sa.String(), nullable=True),
    sa.Column('head_count', sa.Integer(), nullable=False),
    sa.Column('price_per_head', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('eid_ref', sa.String(), nullable=True),
    sa.Column('freight_per_head', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('other_cost_per_kg', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('implied_price_per_kg', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('dnbp_publication_line_id', sa.UUID(), nullable=True),
    sa.Column('dnbp_at_entry', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('variance_per_kg', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('is_breach', sa.Boolean(), nullable=False),
    sa.Column('breach_reason', sa.String(), nullable=True),
    sa.Column('client_uuid', sa.UUID(), nullable=False),
    sa.Column('client_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_status', sa.Enum('SYNCED', 'CONFLICT', name='buy_entry_sync_status'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dnbp_publication_line_id'], ['dnbp_publication_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buy_entries_buyer_id'), 'buy_entries', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_buy_entries_client_uuid'), 'buy_entries', ['client_uuid'], unique=True)
    op.create_index(op.f('ix_buy_entries_trade_date'), 'buy_entries', ['trade_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_buy_entries_trade_date'), table_name='buy_entries')
    op.drop_index(op.f('ix_buy_entries_client_uuid'), table_name='buy_entries')
    op.drop_index(op.f('ix_buy_entries_buyer_id'), table_name='buy_entries')
    op.drop_table('buy_entries')
    op.drop_index(op.f('ix_dnbp_publication_lines_publication_id'), table_name='dnbp_publication_lines')
    op.drop_table('dnbp_publication_lines')
    op.drop_index(op.f('ix_dnbp_publication_deliveries_publication_id'), table_name='dnbp_publication_deliveries')
    op.drop_index(op.f('ix_dnbp_publication_deliveries_buyer_id'), table_name='dnbp_publication_deliveries')
    op.drop_table('dnbp_publication_deliveries')
    op.drop_index(op.f('ix_dnbp_publications_snapshot_id'), table_name='dnbp_publications')
    op.drop_index(op.f('ix_dnbp_publications_published_at'), table_name='dnbp_publications')
    op.drop_index(op.f('ix_dnbp_publications_org_id'), table_name='dnbp_publications')
    op.drop_table('dnbp_publications')
    op.drop_index(op.f('ix_push_subscriptions_user_id'), table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    # ### end Alembic commands ###

    # NOT auto generated: dropping a table does not drop the Postgres ENUM
    # type its column used (same fix as the two earlier migrations).
    sa.Enum(name='buy_entry_sync_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='delivery_channel').drop(op.get_bind(), checkfirst=True)
