"""phase2 ingestion tables

Revision ID: 281aa5f944b6
Revises: 3bd1f326b7bf
Create Date: 2026-09-07 19:12:46.732005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '281aa5f944b6'
down_revision: Union[str, None] = '3bd1f326b7bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_snapshots',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=True),
    sa.Column('source_filename', sa.String(), nullable=False),
    sa.Column('source_sha256', sa.String(), nullable=False),
    sa.Column('object_storage_key', sa.String(), nullable=False),
    sa.Column('detected_layout', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('abattoir_reference_tables', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parser_version', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PARSED', 'CALCULATED', 'PUBLISHED', 'SUPERSEDED', name='snapshot_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_snapshots_source_sha256'), 'order_snapshots', ['source_sha256'], unique=False)
    op.create_table('order_lines',
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('lifecycle', sa.Enum('ACTIVE', 'LOADED', name='lifecycle'), nullable=False),
    sa.Column('contract_no', sa.String(), nullable=True),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('species', sa.String(), nullable=True),
    sa.Column('loadout_date', sa.Date(), nullable=True),
    sa.Column('qty_kg', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('avg_price_aud', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('amount_aud', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('product_type', sa.String(), nullable=True),
    sa.Column('incoterm', sa.Enum('CIF', 'FAS', name='incoterm'), nullable=True),
    sa.Column('nrv_per_kg', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('expected_livestock_cost_per_kg', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('pack_cost_ph', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('offal_return_ph', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('skin_return_ph', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('avg_weight_kg', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('mom_ph', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('deposit_received', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('dnbp_benchmark', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('benchmark_method', sa.Enum('GAYAN_FIXED_COST', 'FINANCIER_MARGIN', 'UNKNOWN', name='benchmark_method'), nullable=True),
    sa.Column('estimated_heads', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('total_livestock_cost', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('value_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['order_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_lines_contract_no'), 'order_lines', ['contract_no'], unique=False)
    op.create_index(op.f('ix_order_lines_lifecycle'), 'order_lines', ['lifecycle'], unique=False)
    op.create_index(op.f('ix_order_lines_snapshot_id'), 'order_lines', ['snapshot_id'], unique=False)
    op.create_table('correction_requests',
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('order_line_id', sa.UUID(), nullable=False),
    sa.Column('raised_by', sa.UUID(), nullable=False),
    sa.Column('raised_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('column_ref', sa.String(), nullable=False),
    sa.Column('issue_code', sa.String(), nullable=False),
    sa.Column('detail', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', 'WITHDRAWN', name='correction_status'), nullable=False),
    sa.Column('resolved_by_snapshot_id', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_line_id'], ['order_lines.id'], ),
    sa.ForeignKeyConstraint(['raised_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_snapshot_id'], ['order_snapshots.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['order_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_correction_requests_order_line_id'), 'correction_requests', ['order_line_id'], unique=False)
    op.create_index(op.f('ix_correction_requests_snapshot_id'), 'correction_requests', ['snapshot_id'], unique=False)
    op.create_index(op.f('ix_correction_requests_status'), 'correction_requests', ['status'], unique=False)
    op.create_table('order_workings',
    sa.Column('order_line_id', sa.UUID(), nullable=False),
    sa.Column('engine_version', sa.String(), nullable=False),
    sa.Column('ref_data_version', sa.String(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('adjusted_price_per_kg', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('pack_cost_per_kg', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('offal_return_per_kg', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('skin_return_per_kg', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('profit_on_peter_costs', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('bing_dnbp', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('bing_dnbp_factor_used', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('bing_dnbp_inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('profit_on_bing_dnbp', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('diff_vs_benchmark', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('diff_vs_peter', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('supporting_analysis_complete', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_line_id'], ['order_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_workings_order_line_id'), 'order_workings', ['order_line_id'], unique=True)
    op.create_table('validation_issues',
    sa.Column('order_line_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('severity', sa.Enum('BLOCK', 'CORRECTION', 'WARN', 'INFO', name='issue_severity'), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('column_ref', sa.String(), nullable=True),
    sa.Column('acknowledged_by', sa.UUID(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_line_id'], ['order_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_issues_code'), 'validation_issues', ['code'], unique=False)
    op.create_index(op.f('ix_validation_issues_order_line_id'), 'validation_issues', ['order_line_id'], unique=False)
    # ### end Alembic commands ###

    # --- Constraint 1 (§1.2, §8, non-negotiable #1) ---------------------
    # order_lines is genuinely immutable, not merely un-updated by
    # convention: the application's own DB role (docker-compose.yml /
    # .env.example: "livestock") loses UPDATE/DELETE outright, and a
    # trigger raises as belt-and-braces even if a future migration
    # mistakenly re-grants it. A correction is always a new snapshot.
    op.execute("REVOKE UPDATE, DELETE ON order_lines FROM livestock")
    op.execute(
        """
        CREATE FUNCTION forbid_order_line_mutation() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'order_lines is immutable -- a correction is a new snapshot, never an edit';
        END;
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        """
        CREATE TRIGGER order_lines_no_mutation
            BEFORE UPDATE OR DELETE ON order_lines
            FOR EACH ROW EXECUTE FUNCTION forbid_order_line_mutation()
        """
    )

    # --- §5.3/§8 ----------------------------------------------------------
    # order_workings may exist ONLY for an ACTIVE order_line — structurally
    # enforced, not merely because domain.engine.workings returns None for
    # a LOADED line. The partial-unique behaviour (one workings row per
    # line) is already the plain unique index created above.
    op.execute(
        """
        CREATE FUNCTION forbid_workings_for_loaded_line() RETURNS trigger AS $$
        DECLARE
            line_lifecycle lifecycle;
        BEGIN
            SELECT lifecycle INTO line_lifecycle FROM order_lines WHERE id = NEW.order_line_id;
            IF line_lifecycle IS DISTINCT FROM 'ACTIVE' THEN
                RAISE EXCEPTION 'order_workings may only be created for an ACTIVE order_line (got %)', line_lifecycle;
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        """
        CREATE TRIGGER order_workings_active_only
            BEFORE INSERT OR UPDATE ON order_workings
            FOR EACH ROW EXECUTE FUNCTION forbid_workings_for_loaded_line()
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS order_workings_active_only ON order_workings")
    op.execute("DROP FUNCTION IF EXISTS forbid_workings_for_loaded_line()")
    op.execute("DROP TRIGGER IF EXISTS order_lines_no_mutation ON order_lines")
    op.execute("DROP FUNCTION IF EXISTS forbid_order_line_mutation()")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_issues_order_line_id'), table_name='validation_issues')
    op.drop_index(op.f('ix_validation_issues_code'), table_name='validation_issues')
    op.drop_table('validation_issues')
    op.drop_index(op.f('ix_order_workings_order_line_id'), table_name='order_workings')
    op.drop_table('order_workings')
    op.drop_index(op.f('ix_correction_requests_status'), table_name='correction_requests')
    op.drop_index(op.f('ix_correction_requests_snapshot_id'), table_name='correction_requests')
    op.drop_index(op.f('ix_correction_requests_order_line_id'), table_name='correction_requests')
    op.drop_table('correction_requests')
    op.drop_index(op.f('ix_order_lines_snapshot_id'), table_name='order_lines')
    op.drop_index(op.f('ix_order_lines_lifecycle'), table_name='order_lines')
    op.drop_index(op.f('ix_order_lines_contract_no'), table_name='order_lines')
    op.drop_table('order_lines')
    op.drop_index(op.f('ix_order_snapshots_source_sha256'), table_name='order_snapshots')
    op.drop_table('order_snapshots')
    # ### end Alembic commands ###

    # NOT auto generated: dropping a table does not drop the Postgres ENUM
    # type its column used (same fix as the first migration).
    sa.Enum(name='issue_severity').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='correction_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='benchmark_method').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='incoterm').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='lifecycle').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='snapshot_status').drop(op.get_bind(), checkfirst=True)
