"""phase3b_reference_data_and_registries

Revision ID: 4011983f89e6
Revises: 1a0dff07b31d
Create Date: 2026-09-08 12:15:57.771977

Creates the reference-data and registry tables and seeds the two OPEN
registries (species, product types) with generic starting rows. It does NOT
seed any DNBP parameters: the CIF buffer, DNBP factors and standard weights
are business-confidential, so a new database has no reference-data version
until an operator creates one (scripts/seed_reference_data.py --file <path>
for a dev database, or the Reference Data screen). The app reports
NO_ACTIVE_REFERENCE_DATA until then.
"""
from datetime import UTC, datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '4011983f89e6'
down_revision: Union[str, None] = '1a0dff07b31d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Open registries (PRD 6.9): a starting set, not a limit — admin-managed at runtime.
_SPECIES = ["SHEEP", "LAMB", "GOAT", "VEAL", "MUTTON"]
_PRODUCT_TYPES = ["CCS", "6 WAY", "FULL BONE"]


def _seed_registries() -> None:
    now = datetime.now(UTC)

    species_table = sa.table(
        "species_registry",
        sa.column("code", sa.String()),
        sa.column("display_name", sa.String()),
        sa.column("is_active", sa.Boolean()),
        sa.column("created_by", sa.UUID()),
        sa.column("created_at", sa.DateTime(timezone=True)),
        sa.column("updated_at", sa.DateTime(timezone=True)),
    )
    op.bulk_insert(
        species_table,
        [
            {
                "code": code,
                "display_name": code.title(),
                "is_active": True,
                "created_by": None,
                "created_at": now,
                "updated_at": now,
            }
            for code in _SPECIES
        ],
    )

    product_type_table = sa.table(
        "product_type_registry",
        sa.column("code", sa.String()),
        sa.column("display_name", sa.String()),
        sa.column("is_active", sa.Boolean()),
        sa.column("created_by", sa.UUID()),
        sa.column("created_at", sa.DateTime(timezone=True)),
        sa.column("updated_at", sa.DateTime(timezone=True)),
    )
    op.bulk_insert(
        product_type_table,
        [
            {
                "code": code,
                "display_name": code,  # e.g. "6 WAY", "CCS" — title-casing would mangle the acronym
                "is_active": True,
                "created_by": None,
                "created_at": now,
                "updated_at": now,
            }
            for code in _PRODUCT_TYPES
        ],
    )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_type_registry',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('reference_data_versions',
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('impact_previewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reference_data_versions_is_active'), 'reference_data_versions', ['is_active'], unique=False)
    op.create_table('species_registry',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('reference_data_drift',
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('table_key', sa.String(), nullable=False),
    sa.Column('key1', sa.String(), nullable=False),
    sa.Column('old_value', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('new_value', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_by', sa.UUID(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['order_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reference_data_drift_snapshot_id'), 'reference_data_drift', ['snapshot_id'], unique=False)
    op.create_table('reference_data_entries',
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('table_key', sa.Enum('CIF_BUFFER_PER_KG', 'DNBP_FACTOR', 'STANDARD_WEIGHT', name='reference_data_table_key'), nullable=False),
    sa.Column('key1', sa.String(), nullable=True),
    sa.Column('key2', sa.String(), nullable=True),
    sa.Column('value', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['reference_data_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reference_data_entries_version_id'), 'reference_data_entries', ['version_id'], unique=False)
    # ### end Alembic commands ###

    _seed_registries()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reference_data_entries_version_id'), table_name='reference_data_entries')
    op.drop_table('reference_data_entries')
    op.drop_index(op.f('ix_reference_data_drift_snapshot_id'), table_name='reference_data_drift')
    op.drop_table('reference_data_drift')
    op.drop_table('species_registry')
    op.drop_index(op.f('ix_reference_data_versions_is_active'), table_name='reference_data_versions')
    op.drop_table('reference_data_versions')
    op.drop_table('product_type_registry')
    # ### end Alembic commands ###
    # Autogenerate drops the table but never the enum type behind
    # table_key — without this, a later re-upgrade fails with
    # "type reference_data_table_key already exists" (found by actually
    # running the down/up cycle, not just eyeballing the diff).
    sa.Enum(name='reference_data_table_key').drop(op.get_bind(), checkfirst=True)
