"""market observations

Revision ID: 5aa63ef7b94b
Revises: 1e825bf814f2
Create Date: 2026-09-17 18:36:52.403730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5aa63ef7b94b'
down_revision: Union[str, None] = '1e825bf814f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_observations',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('observer_id', sa.UUID(), nullable=False),
    sa.Column('saleyard', sa.String(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('species', sa.String(), nullable=False),
    sa.Column('competitor_name', sa.String(), nullable=False),
    sa.Column('agent', sa.String(), nullable=True),
    sa.Column('pen', sa.String(), nullable=True),
    sa.Column('head_count', sa.Integer(), nullable=False),
    sa.Column('price_per_head', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('implied_price_per_kg', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('is_estimated', sa.Boolean(), nullable=False),
    sa.Column('client_uuid', sa.UUID(), nullable=False),
    sa.Column('client_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_status', sa.Enum('SYNCED', 'CONFLICT', name='market_observation_sync_status'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['observer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_observations_client_uuid'), 'market_observations', ['client_uuid'], unique=True)
    op.create_index(op.f('ix_market_observations_observer_id'), 'market_observations', ['observer_id'], unique=False)
    op.create_index(op.f('ix_market_observations_org_id'), 'market_observations', ['org_id'], unique=False)
    op.create_index(op.f('ix_market_observations_trade_date'), 'market_observations', ['trade_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_observations_trade_date'), table_name='market_observations')
    op.drop_index(op.f('ix_market_observations_org_id'), table_name='market_observations')
    op.drop_index(op.f('ix_market_observations_observer_id'), table_name='market_observations')
    op.drop_index(op.f('ix_market_observations_client_uuid'), table_name='market_observations')
    op.drop_table('market_observations')
    # ### end Alembic commands ###
