"""dnbp_publication_line_previous_price

Revision ID: 914773cb42d7
Revises: da0b93835c77
Create Date: 2026-09-17 03:50:00.462946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '914773cb42d7'
down_revision: Union[str, None] = 'da0b93835c77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dnbp_publication_lines', sa.Column('previous_dnbp_per_kg', sa.Numeric(precision=18, scale=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dnbp_publication_lines', 'previous_dnbp_per_kg')
    # ### end Alembic commands ###
