"""order_issue_acknowledgments

Revision ID: cb7256290919
Revises: 842bcc56ffef
Create Date: 2026-09-16 12:09:06.354168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb7256290919'
down_revision: Union[str, None] = '842bcc56ffef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_issue_acknowledgments',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('contract_no', sa.String(), nullable=True),
    sa.Column('species', sa.String(), nullable=True),
    sa.Column('product_type', sa.String(), nullable=True),
    sa.Column('incoterm', sa.String(), nullable=True),
    sa.Column('issue_code', sa.String(), nullable=False),
    sa.Column('column_ref', sa.String(), nullable=True),
    sa.Column('fingerprint', sa.String(), nullable=False),
    sa.Column('acknowledged_by', sa.UUID(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_confirmed_snapshot_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['last_confirmed_snapshot_id'], ['order_snapshots.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'contract_no', 'species', 'product_type', 'incoterm', 'issue_code', 'column_ref', name='uq_order_issue_ack_identity')
    )
    op.create_index(op.f('ix_order_issue_acknowledgments_issue_code'), 'order_issue_acknowledgments', ['issue_code'], unique=False)
    op.create_index(op.f('ix_order_issue_acknowledgments_org_id'), 'order_issue_acknowledgments', ['org_id'], unique=False)
    op.add_column(
        'validation_issues',
        sa.Column('carried_forward', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('validation_issues', 'carried_forward', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('validation_issues', 'carried_forward')
    op.drop_index(op.f('ix_order_issue_acknowledgments_org_id'), table_name='order_issue_acknowledgments')
    op.drop_index(op.f('ix_order_issue_acknowledgments_issue_code'), table_name='order_issue_acknowledgments')
    op.drop_table('order_issue_acknowledgments')
    # ### end Alembic commands ###
