"""dnbp_publication_buyer_notified

Revision ID: da0b93835c77
Revises: cb7256290919
Create Date: 2026-09-16 12:45:38.760160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da0b93835c77'
down_revision: Union[str, None] = 'cb7256290919'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows as True — every publication
    # before this feature existed did in fact send a buyer push unconditionally.
    op.add_column(
        'dnbp_publications',
        sa.Column('buyer_notified', sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    op.alter_column('dnbp_publications', 'buyer_notified', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dnbp_publications', 'buyer_notified')
    # ### end Alembic commands ###
