"""phase4_buy_instruction_tables

Revision ID: ee1da357cc3b
Revises: 4011983f89e6
Create Date: 2026-09-08 15:22:06.586686

§8, §13.1 — buy_instructions/buy_instruction_lines per the PRD's literal
diagram, plus buy_instruction_line_fills (beyond that diagram, same
documented-deviation pattern as Phase 3's dnbp_publication_deliveries): an
open-ended, unbounded list of manual reconciliation fills per line, not
fixed "Buy 1/2/3" columns — confirmed with Terence, since buy_entries carry
no order/contract reference at all.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee1da357cc3b'
down_revision: Union[str, None] = '4011983f89e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buy_instructions',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('instruction_no', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('publication_id', sa.UUID(), nullable=False),
    sa.Column('prepared_by', sa.UUID(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ISSUED', 'ACKNOWLEDGED', 'RECONCILED', name='buy_instruction_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['prepared_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['publication_id'], ['dnbp_publications.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['order_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buy_instructions_instruction_no'), 'buy_instructions', ['instruction_no'], unique=False)
    op.create_index(op.f('ix_buy_instructions_org_id'), 'buy_instructions', ['org_id'], unique=False)
    op.create_index(op.f('ix_buy_instructions_publication_id'), 'buy_instructions', ['publication_id'], unique=False)
    op.create_index(op.f('ix_buy_instructions_snapshot_id'), 'buy_instructions', ['snapshot_id'], unique=False)
    op.create_index(op.f('ix_buy_instructions_trade_date'), 'buy_instructions', ['trade_date'], unique=False)
    op.create_table('buy_instruction_lines',
    sa.Column('instruction_id', sa.UUID(), nullable=False),
    sa.Column('order_line_id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('contract_no', sa.String(), nullable=True),
    sa.Column('species', sa.String(), nullable=False),
    sa.Column('schw_kg', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('expected_heads', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('weight_requirement_kg', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('dnbp_per_kg', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('peters_expectation', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('expected_livestock_cost', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instruction_id'], ['buy_instructions.id'], ),
    sa.ForeignKeyConstraint(['order_line_id'], ['order_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buy_instruction_lines_instruction_id'), 'buy_instruction_lines', ['instruction_id'], unique=False)
    op.create_table('buy_instruction_line_fills',
    sa.Column('line_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('kg_amount', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('entered_by', sa.UUID(), nullable=False),
    sa.Column('entered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entered_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['line_id'], ['buy_instruction_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buy_instruction_line_fills_line_id'), 'buy_instruction_line_fills', ['line_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_buy_instruction_line_fills_line_id'), table_name='buy_instruction_line_fills')
    op.drop_table('buy_instruction_line_fills')
    op.drop_index(op.f('ix_buy_instruction_lines_instruction_id'), table_name='buy_instruction_lines')
    op.drop_table('buy_instruction_lines')
    op.drop_index(op.f('ix_buy_instructions_trade_date'), table_name='buy_instructions')
    op.drop_index(op.f('ix_buy_instructions_snapshot_id'), table_name='buy_instructions')
    op.drop_index(op.f('ix_buy_instructions_publication_id'), table_name='buy_instructions')
    op.drop_index(op.f('ix_buy_instructions_org_id'), table_name='buy_instructions')
    op.drop_index(op.f('ix_buy_instructions_instruction_no'), table_name='buy_instructions')
    op.drop_table('buy_instructions')
    # ### end Alembic commands ###

    # NOT auto generated: dropping a table does not drop the Postgres ENUM
    # type its column used (same fix as every earlier migration that added
    # an Enum column — see phase3_publication_buyer_tables.py).
    sa.Enum(name='buy_instruction_status').drop(op.get_bind(), checkfirst=True)
